// SPDX-License-Identifier: MIT
/**
 * @file
 * @brief Board support package implementation for on-board status LEDs.
 *
 * @details
 * Keeps LED GPIO binding, polarity conversion, and cached logical state local
 * to this translation unit.
 *
 * Hardware dependency:
 * - Expects LED port/pin symbols generated by CubeMX and exposed via `main.h`.
 *
 * Design note:
 * - API is stateful (`bsp_led_init()` must run first) and not synchronized.
 *   If accessed from multiple RTOS contexts, external serialization is required.
 */
#include "bsp_led.h"

#include <stdbool.h>

#include "main.h"

typedef enum bsp_led_polarity {
  BSP_LED_ACTIVE_HIGH = 0,
  BSP_LED_ACTIVE_LOW = 1,
} bsp_led_polarity_t;

typedef struct bsp_led_output {
  GPIO_TypeDef *port;
  uint16_t pin;
  bsp_led_polarity_t polarity;
} bsp_led_output_t;

static const bsp_led_output_t led_outputs[BSP_LED_COUNT] = {
  { LED_BLUE_L_GPIO_Port, LED_BLUE_L_Pin, BSP_LED_ACTIVE_HIGH },
  { LED_GREEN_L_GPIO_Port, LED_GREEN_L_Pin, BSP_LED_ACTIVE_LOW },
  { LED_RED_L_GPIO_Port, LED_RED_L_Pin, BSP_LED_ACTIVE_LOW },
  { LED_GREEN_R_GPIO_Port, LED_GREEN_R_Pin, BSP_LED_ACTIVE_LOW },
  { LED_RED_R_GPIO_Port, LED_RED_R_Pin, BSP_LED_ACTIVE_LOW },
};

static bool leds_initialized = false;
static bool led_states[BSP_LED_COUNT] = { false };

/**
 * @brief Validate whether the LED identifier maps to the local output table.
 *
 * @param[in] id Candidate LED identifier from caller.
 * @return true if `id` is within [0, BSP_LED_COUNT), otherwise false.
 */
static bool bsp_led_is_valid_id(uint8_t id)
{
  return id < BSP_LED_COUNT;
}

/**
 * @brief Convert logical LED state to electrical GPIO level.
 *
 * @param[in] output LED hardware descriptor with polarity information.
 * @param[in] on Logical LED state where true means on.
 * @return GPIO pin level to drive on the physical pin.
 *
 * @note Active-low LEDs require inverted GPIO levels.
 */
static GPIO_PinState bsp_led_get_pin_state(const bsp_led_output_t *output,
                                           bool on)
{
  if (output->polarity == BSP_LED_ACTIVE_LOW) {
    return on ? GPIO_PIN_RESET : GPIO_PIN_SET;
  }

  return on ? GPIO_PIN_SET : GPIO_PIN_RESET;
}

/**
 * @brief Apply LED logical state to hardware and update cached logical state.
 *
 * @param[in] id Valid LED identifier.
 * @param[in] on Logical target state.
 *
 * @pre `id` must be valid. Caller is responsible for range checks.
 */
static void bsp_led_write(uint8_t id, bool on)
{
  const bsp_led_output_t *output = &led_outputs[id];

  HAL_GPIO_WritePin(output->port, output->pin,
                    bsp_led_get_pin_state(output, on));
  led_states[id] = on;
}

void bsp_led_init(void)
{
  uint8_t index = 0u;

  for (; index < BSP_LED_COUNT; ++index) {
    bsp_led_write(index, false);
  }

  leds_initialized = true;
}

void bsp_led_set(uint8_t id, bool on)
{
  if (!leds_initialized || !bsp_led_is_valid_id(id)) {
    return;
  }

  bsp_led_write(id, on);
}

void bsp_led_toggle(uint8_t id)
{
  if (!leds_initialized || !bsp_led_is_valid_id(id)) {
    return;
  }

  bsp_led_write(id, !led_states[id]);
}
